### ISSUE TITLE
How to run the OpenLTE with USRP N210

### ISSUE THREAD

**Issue by dominicantonyv** [mgp25/OpenLTE#2]
Hi

Could someone please walk me through the steps to run this OpenLTE project. 
Also I would like to know if this project supports **USRP N210**. 

I followed the instruction given under `Running OpenLTE eNodeB` in [readme](https://github.com/mgp25/OpenLTE/blob/master/README.md]). 
But the USRP was not generating any signal. I gave `start` command in 2nd Terminal. But it was failed, dispalyed `Can't Start` and threw some error which I couldn't understand as it was some non-printable characters.

Those who have succeeded in running this application, please help. Also please share the details of the system, USRP and the configuration used to successfully run the project. Thank You.

**Comment by mgp25** [comment]
Hello @dominicantonyv,

**OpenLTE supported USRP Boards [1]:**

- **eNodeB:** B2X0
- **Scan:** B2X0, N-series, rtl-sdr, bladeRF, and hackRF

In your case, you can't use your USRP N210 with the eNodeB.

The configuration we have used can be found in the [readme](https://github.com/mgp25/OpenLTE/issues/url), nevertheless with your USRP, as far as I know, it won't work.

You will need an USRP that uses BUS transport:

<table class="wikitable">
<tr>
<th colspan="7">Ettus Research Devices
</th></tr>
<tr>
<td>
</td>
<td>Transport
</td>
<td>Recommended RF
</td>
<td colspan="2">Frequency Accuracy
</td></tr>
<tr>
<td>B200
</td>
<td rowspan="2">USB 3.0
</td>
<td rowspan="2">Integrated
</td>
<td rowspan="2">TCXO 2.0 ppm
</td>
<td rowspan="6">GPSDO &lt;1 ppb
</td></tr>
<tr>
<td>B210
</td></tr>
<tr>
<td>X300
</td>
<td rowspan="2">1 or 10 Gigabit Ethernet
</td>
<td rowspan="5">SBX, WBX, CBX
</td>
<td rowspan="4">TCXO 2.5 ppm
</td></tr>
<tr>
<td>X310
</td></tr>
<tr>
<td>N200
</td>
<td rowspan="3">1 Gigabit Ethernet
</td></tr>
<tr>
<td>N210
</td></tr>
<tr>
<td>USRP2
</td>
<td>VCXO 20 ppm
</td>
<td>NA
</td></tr></table>

As you can see in the table, supported devices are: B200 and B210.

Regards

--

### References

- [1] Supported USRP Boards. OpenLTE Author: https://sourceforge.net/p/openlte/mailman/message/32342329/

**Comment by dominicantonyv** [comment]
Thanks alot @mgp25 , for the response. 
So the **eNodeB** generates the LTE signal and that can be done only using Bus series USRP, for now..right? Please correct me if I'm wrong. 
What does **Scan** do?

**Comment by mgp25** [comment]
@dominicantonyv Yes, you are right. It is only supported BUS series USRP.

We haven't tried the `scan` application which is the `LTE_fdd_dl_scan`. Probably used to scan LTE spectrum and capture SIB messages. Also can be used for [test captures.](https://github.com/mgp25/OpenLTE#test-captures)

Regards

**Comment by dominicantonyv** [comment]
Thanks @mgp25 . 

I have another USRP (not in hand right now). The model is **USRP 2954** ([http://www.ni.com/en-in/support/model.usrp-2954.html](http://www.ni.com/en-in/support/model.usrp-2954.html)). Can this USRP be used with OpenLTE?

**Comment by mgp25** [comment]
@dominicantonyv 

I don't know if the USRP 2954 [1] will work, you will need to test it. We are using USRP NI 2901  [2] which is detected as USRP B210. You can check that using `uhd_usrp_probe` command:

```
openlte$ uhd_usrp_probe

linux; GNU C++ version 4.8.2; Boost_105400; UHD_003.008.001-42-g8c87a524

-- Operating over USB 3.
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 32.000000 MHz...
-- Actually got clock rate 32.000000 MHz.
-- Performing timer loopback test... pass
-- Setting master clock rate selection to 'automatic'.
  _____________________________________________________
 /
|       Device: B-Series Device
|     _____________________________________________________
|    /
|   |       Mboard: B200
```

--

### References

- [1] USRP-2954 Specifications. National Instruments. http://www.ni.com/pdf/manuals/375725c.pdf
- [2] USRP-2901 Specifications. National Instruments. http://www.ni.com/pdf/manuals/374925c.pdf
