### ISSUE TITLE
GnuRadio 3.8 support

### ISSUE THREAD

**Issue by 5l1v3r1** [mgp25/OpenLTE#5]
Please port openlte to gnuradio 3.8.

**Comment by mgp25** [comment]
Hello @5l1v3r1,

This isn't the official maintainer, this is just a fork with some documentation of mine. The official project can be found here: https://sourceforge.net/projects/openlte/ As far as I know the original author isn't working on OpenLTE anymore. I will leave this issue open in case anyone in interested to port it.

Best regards
