### ISSUE TITLE
SysmoUSIM-SJS1 sim not initiating attach request to network on iPhones

### ISSUE THREAD

**Issue by abiodunwuyi** [mgp25/OpenLTE#6]
Hi,

I am testing sysmoUSIM-SJS1 on iPhones, the USIM was programmed with new IMSIs. SIM attaches to private LTE network on Android devices & LTE routers but does not initiate a connection to the LTE network on iPhones.
Do sysmoUSIM-SJS1 supports iPhones?

Thanks

**Comment by mgp25** [comment]
Hello @abiodunwuyi,

Yes, sysmoUSIM-SJS1 supports iPhone devices. In fact, the tests we did were using an iPhone 6 and an iPhone 7.

Best regards

**Comment by abiodunwuyi** [comment]
Hi @mgp25,

I am testing with iphone 8 & iPhone X, none of the devices connected using  sysmoUSIM-SJS1.
The same iPhones connected to the network using generic test SIMs to our private LTE. What could explain that?

Thanks

**Comment by mgp25** [comment]
Make sure you have programmed the SIM cards accordingly, in the readme you can follow the steps to program the SIM card. Also use the same OP code as the code. If you are using the code of this repository `OP=11111111111111111111111111111111`

Regards
