### ISSUE TITLE
MNC read error in pySim-read.py

### ISSUE THREAD

**Issue by abiodunwuyi** [mgp25/OpenLTE#7]
Hi,
Using the pySim-read.py code for reading SIM dumps, MNC digits are read incorrectly when MNC length is 3 -digits but read correctly when MNC length is 2-digit. Is this a bug in the code? See sample SIM dumps below.
![313410 plmn SIM](https://user-images.githubusercontent.com/25392833/112023296-7d6a0a00-8b09-11eb-8029-87d8123f239a.png)
![00101 plmn SIM](https://user-images.githubusercontent.com/25392833/112023319-822ebe00-8b09-11eb-9c0b-9cdd1009b27f.png)

**Comment by mgp25** [comment]
Hello,

This project is not related with pySIM. You can ask here: https://github.com/osmocom/pysim

Regards
