### ISSUE TITLE
Low latency (Laptop)

### ISSUE THREAD

**Issue by GTRacing65** [mgp25/OpenLTE#8]
OpenLTE is not only requiring a huge amount of processing power, but it also requires a very low latency, Low latency of what? memory latency, CPU latency or dpc latency? Because i want to use OpenLTE on my gaming Laptop (i5 11400h) but Laptops usually have a higher latency than PCs

**Comment by mgp25** [comment]
Low-latency kernel. Basically it needs the configurations to be able to process such amount of samples in realtime.

We used the following hardware:

```
USB 3.0 interface
Modern multicore CPU (Intel Core i5, Core i7 or equivalent with SSE4.1 SSE4.2 and AVX support)
UHD driver installed (for Ettus SDRs)
```

And make all changes in BIOS to provide the best performance of your equipment:

```
Remove all power management features inthe BIOS (sleep states, in particular C-states) and CPU frequency scaling(Intel [SpeedStep](https://twiki.eurecom.fr/twiki/bin/edit/OpenAirInterface/SpeedStep?topicparent=OpenAirInterface.OpenAirKernelMainSetup;nowysiwyg=0)). Insome cases, you can also do this with cpufreqtool.

check this using this command: watch grep \"cpu MHz\" /proc/cpuinfo
have a look at [this link ](http://askubuntu.com/questions/523640/how-i-can-disable-cpu-frequency-scaling-and-set-the-system-to-performance)for further information
you may need to add intel_pstate=disable to the Linux boot options, i.e GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_pstate=disable" in /etc/default/grub, then perform update-grub
```

Reference: https://www.cnblogs.com/jhcelue/p/7305974.html

Regards
